name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # composer install
          # npm install

      - name: Build Project
        run: |
          # npm run build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          echo "${{ env.SSH_USER }}"
          echo "${{ env.SERVER_IP }}"
          echo "${{ github.run_number }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.SSH_USER }}@${{ env.SERVER_IP }} 'cd /var/www && sudo mkdir ${{ env.GITHUB_RUN_NUMBER }}'
