name: Deploy WordPress

on:
  push:
    branches:
      - main

env:
  SSH_USER: ${{ var.SSH_USER }}
  SERVER_IP: ${{ var.SERVER_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # composer install
          # npm install

      - name: Build Project
        run: |
          # npm run build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          echo "$SSH_USER"
          echo "$SERVER_IP"
          echo "${{ github.run_number }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP 'cd /var/www && sudo mkdir ${{ env.GITHUB_RUN_NUMBER }}'
