name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # composer install
          # npm install

      - name: Build Project
        run: |
          # npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          cat ~/.ssh/id_rsa
          echo $SSH_USER
          echo $SERVER_IP
          echo ${{ env.GITHUB_RUN_NUMBER }}
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP 'cd /var/www && sudo mkdir ${{ env.GITHUB_RUN_NUMBER }}'
