name: Deploy WordPress

on:
  push:
    branches:
      - main

env:
  SSH_USER: ${{ vars.SSH_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # composer install
          # npm install

      - name: Build Project
        run: |
          # npm run build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP 'sudo mkdir -p /var/www/${{ github.run_number }}'
          rsync . $SSH_USER@$SERVER_IP:/var/www/${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP 'sudo unlink /var/www/wordpress && sudo ln -s /var/www/${{ github.run_number }} /var/www/wordpress'
