name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # composer install
          # npm install

      - name: Build Project
        run: |
          # npm run build

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SSH_USER@$SERVER_IP 'cd /var/www && sudo mkdir {{ env.GITHUB_RUN_NUMBER }}'
